apiVersion: v1
kind: Pod
metadata:
  name: gpu-rest-tester
spec:
  restartPolicy: Never
  containers:
  - name: gpu-rest-tester
    image: pure/gpu-rest-tester
    imagePullPolicy: IfNotPresent
    env:
    - name: RESTURL
      value: "http://gpu-rest-engine/api/classify"
    - name: CONCURRENCY
      value: "8"
    - name: REQUESTS
      value: "10000"
